### ISSUE TITLE
Cannot log in on Mac OS X

### ISSUE THREAD

**Issue by HybridRbt** [geeeeeeeeek/electronic-wechat#39]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description
OS version 10.11.4 Beta(15E56a); after QR code scanning my WeChat app on iPhone will report success, but Electronic WeChat will stay at the confirm log in screen.

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
I can't get version from that command. I used homebrew to install Electron following guide on this site: 
http://macappstore.org/electron/ 
- Version of Node.js (run `$ node --version`): `v5.7.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by gucheen** [comment]
+1
#41

**Comment by geeeeeeeeek** [comment]
Fixed in #41.

**Comment by HybridRbt** [comment]
Still have the same problem. I cloned the rep and compiled it on my machine as directed, but the problem is the same with the released version.

**Comment by geeeeeeeeek** [comment]
@HybridRbt 能否打开devTools看一下登录时的Network请求

**Comment by HybridRbt** [comment]
@geeeeeeeeek 我不会用 devTools，有具体步骤吗？
